import { BlogPostingJsonLd } from "@/components/JsonLd";
import type { BlogPost } from "@/lib/blog";

// Shared article rendering, used by both the real /blog/[slug] page and the
// /blog/preview/[id] draft-review page — so a draft previewed before
// publishing looks exactly like it will once it's live.
export default function BlogPostArticle({
  post,
  banner,
}: {
  post: BlogPost;
  banner?: React.ReactNode;
}) {
  const date = new Date(post.publishedAt);
  const formatted = Number.isNaN(date.getTime())
    ? null
    : date.toLocaleDateString("en-CA", {
        year: "numeric",
        month: "long",
        day: "numeric",
      });

  return (
    <article className="bg-grid-dark mx-auto max-w-3xl px-4 py-20 sm:px-6">
      {banner}

      <BlogPostingJsonLd
        title={post.title}
        description={post.excerpt}
        slug={post.slug}
        publishedAt={post.publishedAt}
        author={post.author}
        coverImage={post.coverImage}
      />

      <header>
        {formatted && (
          <p className="text-sm font-medium uppercase tracking-wide text-slate-400">
            {formatted} &middot; {post.author}
          </p>
        )}
        <h1 className="mt-2 text-4xl font-bold tracking-tight text-white">
          {post.title}
        </h1>
      </header>

      {post.coverImage && (
        // eslint-disable-next-line @next/next/no-img-element -- cover images come from an external, config-time-unknown CMS host
        <img
          src={post.coverImage}
          alt={post.title}
          className="mt-8 aspect-video w-full rounded-xl border border-white/10 object-cover"
        />
      )}

      <div
        className="prose prose-lg prose-invert mt-10 max-w-none prose-headings:font-heading prose-a:text-accent prose-img:rounded-xl prose-strong:text-white"
        // Body HTML is AI-generated by the n8n pipeline and reviewed by a
        // human before being flipped to 'published' — trusted content, not
        // arbitrary user input.
        dangerouslySetInnerHTML={{ __html: post.body }}
      />
    </article>
  );
}
