import { supabase } from "@/lib/supabase";
import { supabaseAdmin } from "@/lib/supabase-admin";

export interface BlogPost {
  title: string;
  slug: string;
  excerpt: string;
  body: string; // full article HTML, generated by the n8n AI pipeline
  coverImage?: string;
  publishedAt: string; // ISO 8601
  author: string;
  seoTitle?: string;
  seoDescription?: string;
  // Only populated by getPostByIdForPreview — the public getPosts/
  // getPostBySlug never return anything but published posts, so this would
  // always just say "published" there and isn't worth carrying.
  status?: "draft" | "published";
}

// ISR window (seconds) for the blog list/post pages. Documents the value —
// it is NOT imported and used as `export const revalidate = ...` in those
// page files, because Next.js requires route segment config exports to be
// static literals parsed at build time (it never executes the import), so
// referencing this constant there fails the build with "Invalid segment
// configuration export detected." Each page hardcodes `revalidate = 300`
// itself instead; keep both in sync by hand if this ever changes.
export const BLOG_REVALIDATE_SECONDS = 300;

interface BlogPostRow {
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  cover_image: string | null;
  published_at: string | null;
  created_at: string;
  author: string;
  meta_title: string | null;
  meta_description: string | null;
  status?: "draft" | "published";
}

const POST_COLUMNS =
  "title, slug, excerpt, content, cover_image, published_at, created_at, author, meta_title, meta_description";

function rowToPost(row: BlogPostRow): BlogPost {
  return {
    title: row.title,
    slug: row.slug,
    excerpt: row.excerpt,
    body: row.content,
    coverImage: row.cover_image ?? undefined,
    publishedAt: row.published_at ?? row.created_at,
    author: row.author,
    seoTitle: row.meta_title ?? undefined,
    seoDescription: row.meta_description ?? undefined,
    status: row.status,
  };
}

export async function getPosts(): Promise<BlogPost[]> {
  if (!supabase) return [];

  const { data, error } = await supabase
    .from("blog_posts")
    .select(POST_COLUMNS)
    .eq("status", "published")
    .order("published_at", { ascending: false });

  // Fail soft — a Supabase outage or misconfiguration shouldn't break the
  // page, same contract the old n8n-fed REST fetch had.
  if (error || !data) return [];
  return data.map(rowToPost);
}

export async function getPostBySlug(slug: string): Promise<BlogPost | null> {
  if (!supabase) return null;

  const { data, error } = await supabase
    .from("blog_posts")
    .select(POST_COLUMNS)
    .eq("slug", slug)
    .eq("status", "published")
    .maybeSingle();

  if (error || !data) return null;
  return rowToPost(data);
}

// Fetches a post by id regardless of status (draft or published), using the
// service-role client so RLS doesn't hide unpublished rows. Used only by
// the /blog/preview/[id] route — never call this from anything reachable
// without the preview token check that route performs.
export async function getPostByIdForPreview(id: string): Promise<BlogPost | null> {
  if (!supabaseAdmin) return null;

  const { data, error } = await supabaseAdmin
    .from("blog_posts")
    .select(`${POST_COLUMNS}, status`)
    .eq("id", id)
    .maybeSingle();

  if (error || !data) return null;
  return rowToPost(data);
}
