import { supabase } from "@/lib/supabase";

export interface BlogPost {
  title: string;
  slug: string;
  excerpt: string;
  body: string; // full article HTML, generated by the n8n AI pipeline
  coverImage?: string;
  publishedAt: string; // ISO 8601
  author: string;
  seoTitle?: string;
  seoDescription?: string;
}

// ISR window (seconds) for the blog list/post pages — set as `export const
// revalidate` in those page files (Supabase's client calls the global fetch
// under the hood, but Next 15+ no longer caches fetch by default, so page-
// level revalidate is the reliable way to get the same ISR behavior the old
// REST-based fetch had).
export const BLOG_REVALIDATE_SECONDS = 300;

interface BlogPostRow {
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  cover_image: string | null;
  published_at: string | null;
  created_at: string;
  author: string;
  meta_title: string | null;
  meta_description: string | null;
}

const POST_COLUMNS =
  "title, slug, excerpt, content, cover_image, published_at, created_at, author, meta_title, meta_description";

function rowToPost(row: BlogPostRow): BlogPost {
  return {
    title: row.title,
    slug: row.slug,
    excerpt: row.excerpt,
    body: row.content,
    coverImage: row.cover_image ?? undefined,
    publishedAt: row.published_at ?? row.created_at,
    author: row.author,
    seoTitle: row.meta_title ?? undefined,
    seoDescription: row.meta_description ?? undefined,
  };
}

export async function getPosts(): Promise<BlogPost[]> {
  if (!supabase) return [];

  const { data, error } = await supabase
    .from("blog_posts")
    .select(POST_COLUMNS)
    .eq("status", "published")
    .order("published_at", { ascending: false });

  // Fail soft — a Supabase outage or misconfiguration shouldn't break the
  // page, same contract the old n8n-fed REST fetch had.
  if (error || !data) return [];
  return data.map(rowToPost);
}

export async function getPostBySlug(slug: string): Promise<BlogPost | null> {
  if (!supabase) return null;

  const { data, error } = await supabase
    .from("blog_posts")
    .select(POST_COLUMNS)
    .eq("slug", slug)
    .eq("status", "published")
    .maybeSingle();

  if (error || !data) return null;
  return rowToPost(data);
}
